#!/usr/bin/env sh

PG_DB=webdev21videos2
PG_PASSWORD=`head -c 18 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 12`
PG_SERVICE_NAME=postgres
PG_USER=webdev21videos2_user

echo "ALLOWED_HOSTS=*
CELERY_BROKER_URL=redis://redis:6379/0
CELERY_FLOWER_PASSWORD=awake
CELERY_FLOWER_USER=awake
DATABASE_URL=postgres://$PG_USER:$PG_PASSWORD@$PG_SERVICE_NAME:5432/$PG_DB
DEBUG=true
GRID_ENGINE_DELETE_CMD=/app/bin/qdel
GRID_ENGINE_STATUS_CMD=/app/bin/qstat
GRID_ENGINE_SUBMIT_CMD=/app/bin/qsub
MEDIA_ROOT=/media/
POSTGRES_DB=$PG_DB
POSTGRES_PASSWORD=$PG_PASSWORD
POSTGRES_USER=$PG_USER
POSTGRES_HOST=$PG_SERVICE_NAME
REDIS_URL=redis://redis:6379/0
SCC_FTPLUS_PATH=/tmp/
SCC_MAX_HIGH_JOBS=50
SCC_MAX_LOW_JOBS=25
SCC_MAX_NORMAL_JOBS=25
SCC_WEBHOOK_COMPLETED_JOB_API_TOKEN=
SCC_WEBHOOK_COMPLETED_JOB_URL=http://ftplus.bu.edu:8080/ftplus/scc-api/%s/
SCC_WEBHOOK_ENABLED=false
SECRET_KEY=`head -c 75 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 50`" > .docker-env
