version: '3.6'

services:

  redis:
    image: redis:3.2

  django:
    build:
      context: .
      dockerfile: ./docker/django-sge-submit-host/Dockerfile
    depends_on:
      - redis
    env_file: ./.docker-env
    ports:
      - "8000:8000"
    volumes:
      - nfs-ftplus:/projectnb/ftplus

  scheduler:
    build:
      context: .
      dockerfile: ./docker/django-sge-submit-host/Dockerfile
    command: /start-scheduler
    depends_on:
      - redis
    env_file: ./.docker-env
    volumes:
      - nfs-ftplus:/projectnb/ftplus

  worker:
    build:
      context: .
      dockerfile: ./docker/django-sge-submit-host/Dockerfile
    command: celery -A config worker --queues celery -l INFO
    depends_on:
      - redis
    env_file: ./.docker-env
    volumes:
      - nfs-ftplus:/projectnb/ftplus

volumes:
  nfs-ftplus:
    external: true
    name: nfs-ftplus