version: '3.6'

services:

  # The "postgres" database can be removed after we have a production
  # database to point it to
  # postgres:
  #   image: postgres:10.4-alpine
  #   env_file: ./.docker-env
  #   volumes:
  #     - ./postgres_data_dev:/var/lib/postgresql/data
  #     - ./postgres_backup_dev:/backups

  redis:
    image: redis:3.2

  django:
    build:
      context: .
      dockerfile: ./docker/django-sge-submit-host/Dockerfile
    depends_on:
      # - postgres
      - redis
    env_file: ./.docker-env
    ports:
      - "8000:8000"

  scheduler:
    build:
      context: .
      dockerfile: ./docker/django-sge-submit-host/Dockerfile
    command: /start-scheduler
    depends_on:
      # - postgres
      - redis
    env_file: ./.docker-env

  worker:
    build:
      context: .
      dockerfile: ./docker/django-sge-submit-host/Dockerfile
    command: celery -A config worker --queues celery -l INFO
    depends_on:
      # - postgres
      - redis
    env_file: ./.docker-env

  # flower:
  #   image: mher/flower
  #   command: /start-flower
  #   depends_on:
  #     - redis
  #   env_file: ./.docker-env
  #   ports:
  #     - "5555:5555"
