version: "3.6"

services:

  redis:
    image: redis:3.2

  django:
    build:
      context: .
      dockerfile: ./docker/django-sge-submit-host/Dockerfile
    depends_on:
      - redis
    env_file: ./.docker-env
    hostname: ftplus-dev.bu.edu
    ports:
      - "8000:8000"
    # user: "ftsubmit:ftplus"
    volumes:
      - nfs-ftplus:/projectnb/ftplus

  scheduler:
    build:
      context: .
      dockerfile: ./docker/django-sge-submit-host/Dockerfile
    command: /start-scheduler.sh
    depends_on:
      - redis
    env_file: ./.docker-env
    volumes:
      - nfs-ftplus:/projectnb/ftplus

  worker:
    build:
      context: .
      dockerfile: ./docker/django-sge-submit-host/Dockerfile
    command: /start-worker.sh
    depends_on:
      - redis
    env_file: ./.docker-env
    hostname: ftplus-dev.bu.edu
    user: "ftsubmit:ftplus"
    volumes:
      - nfs-ftplus:/projectnb/ftplus

volumes:
  nfs-ftplus:
    external: true
    name: nfs-ftplus
