version: '3.6'

services:

  postgres:
    image: postgres:10.4-alpine
    env_file: ./.docker-env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  redis:
    image: redis:3.2

  django:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    depends_on:
      - redis
      - postgres
    env_file: ./.docker-env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  celerybeat:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: /start-celerybeat
    depends_on:
      - redis
      - postgres
    env_file: ./.docker-env
    volumes:
      - ./src:/app

  celeryworker:
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    command: celery -A config worker -l INFO
    depends_on:
      - redis
      - postgres
    env_file: ./.docker-env
    volumes:
      - ./src:/app

  flower:
    image: mher/flower
    # TODO: switch back when flower supports Celery 5.0
    # build:
    #   context: .
    #   dockerfile: ./docker/django/Dockerfile
    command: /start-flower
    depends_on:
      - redis
      - postgres
    env_file: ./.docker-env
    ports:
      - "5555:5555"
    volumes:
      - ./src:/app


volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}
