version: '3.6'

services:

  redis:
    image: redis:3.2

  caddy:
    image: "caddy:2.2.1"
    depends_on:
      - django
    env_file: ./.docker-env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile  # configuration
      - caddy-config:/config  # configuration autosaves
      - caddy-data:/data  # saving certificates
    #   - django-static:/var/www/django/static  # serving django's statics
    #   - django-media:/var/www/django/media  # serving django's media

  django:
    depends_on:
      - redis
    env_file: ./.docker-env
    hostname: ftplus.bu.edu
    image: ghcr.io/vajda-lab/scc-api:latest
    ports:
      - "8000:8000"
    # user: "ftsubmit:ftplus"
    volumes:
      - nfs-ftplus:/projectnb/ftplus

  scheduler:
    # build:
    #   context: .
    #   dockerfile: ./docker/sge-submit-host/Dockerfile
    command: /start-scheduler.sh
    depends_on:
      - redis
    env_file: ./.docker-env
    image: ghcr.io/vajda-lab/scc-api:latest
    volumes:
      - nfs-ftplus:/projectnb/ftplus

  worker:
    # build:
    #   context: .
    #   dockerfile: ./docker/sge-submit-host/Dockerfile
    command: /start-worker.sh
    depends_on:
      - redis
    env_file: ./.docker-env
    hostname: ftplus.bu.edu
    image: ghcr.io/vajda-lab/scc-api:latest
    user: "ftsubmit:ftplus"
    volumes:
      - nfs-ftplus:/projectnb/ftplus

volumes:
  caddy-config:
  caddy-data:
  # django-media:
  # django-locale:
  nfs-ftplus:
    name: nfs-ftplus
    driver_opts:
      type: "nfs"
      o: "addr=scc-fs.bu.edu,hard,nolock,rw"
      device: ":/gpfs4/projectnb/ftplus"
