version: '3.6'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    image: postgres:10.4-alpine
    env_file: ./.docker-env
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
      - postgres_backup_dev:/backups

  django:
    &django
    build:
      context: .
      dockerfile: ./docker/django/Dockerfile
    depends_on:
      - postgres
    env_file: ./.docker-env
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app

  redis:
    image: redis:3.2

  celeryworker:
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: celery -A config worker -l INFO

  celerybeat:
    <<: *django
    depends_on:
      - redis
      - postgres
    ports: []
    command: /start-celerybeat

  flower:
    <<: *django
    ports:
      - "5555:5555"
    command: /start-flower

