# Generated by Django 2.1.15 on 2020-03-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="affiliation",
            field=models.CharField(
                choices=[("I", "Industry"), ("A", "Academia"), ("O", "Other")],
                default="I",
                max_length=1,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="notes",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="organization",
            field=models.CharField(default="Boston University", max_length=250),
            preserve_default=False,
        ),
    ]
