# Generated by Django 2.1.15 on 2020-03-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_auto_20200302_2227"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="affiliation",
            field=models.CharField(
                choices=[("I", "Industry"), ("A", "Academia"), ("O", "Other")],
                default="O",
                max_length=1,
            ),
        ),
    ]
