# Generated by Django 2.1.15 on 2020-03-17 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_auto_20200303_2137"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="max_job_submission",
            field=models.IntegerField(default=20),
        ),
    ]
