# Generated by Django 3.1.7 on 2021-03-24 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_user_max_job_submission"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="priority",
            field=models.IntegerField(
                choices=[(0, "low"), (1, "normal"), (2, "high")], default=0
            ),
        ),
    ]
