# Generated by Django 2.1.9 on 2019-06-06 17:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sccApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
