# Generated by Django 3.1.7 on 2021-04-16 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sccApi', '0021_auto_20210415_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
