name: CI

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - develop
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-18.04
    name: Tests with Python

    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Test with pytest
        env:
          CELERY_BROKER_URL: 'redis://redis:6379/0'
          CELERY_FLOWER_PASSWORD: 'celery'
          CELERY_FLOWER_USER: 'celery'
          DATABASE_URL: 'postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}/postgres'
          DEBUG: false
          GRID_ENGINE_DELETE_CMD: '/home/runner/work/scc-api/scc-api/src/bin/qdel'
          GRID_ENGINE_STATUS_CMD: '/home/runner/work/scc-api/scc-api/src/bin/qstat'
          GRID_ENGINE_SUBMIT_CMD: '/home/runner/work/scc-api/scc-api/src/bin/qsub'
          REDIS_URL: 'redis://redis:6379/0'
          SECRET_KEY: 'this-is-for-testing-only'

        run: |
          python -m pytest src

      - name: Lints Python
        run: |
          black --check .

      - name: Lints HTML templates
        run: |
          curlylint src/templates/
