# Generated by Django 3.1.7 on 2021-03-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_job_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="priority",
            field=models.IntegerField(
                choices=[(-1, "low"), (0, "normal"), (1, "high")], default=0
            ),
        ),
    ]
