# Generated by Django 3.1.7 on 2021-04-23 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0023_joblog"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_ja_task_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
