# Generated by Django 3.2.4 on 2021-07-06 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_auto_20210423_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='imported',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_ja_task_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
