# Generated by Django 3.2.5 on 2021-08-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_job_scc_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='sge_task_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
    ]
