# Generated by Django 3.2.5 on 2021-08-26 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0031_alter_job_sge_task_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="callback_job_id",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
